org: likezhang
app: podtree-serverless
service: podtree-serverless
frameworkVersion: '4'

plugins:
  - serverless-webpack
  - serverless-offline

build:
  esbuild: false

custom:
  serverless-offline:
    httpPort: 5001
    lambdaPort: 5002
    httpsProtocol: ./certs
  # stage: ${opt:stage, 'dev'} # Default to 'dev' if no stage is specified
  # isDev: ${self:custom.stage} == 'dev'
layers:
  mongodbLayer:
    path: mongodb-layer
    compatibleRuntimes:
      - nodejs18.x
      - nodejs20.x
      - nodejs22.x
    description: "MongoDB Node.js driver for Lambda"
# package:
#   include:
#     - node_modules/**
#     - db/**
#     - utils/**
#     - models/**
#     - lambdas/**
#     - const.js
package:
  include:
    - .env
provider:
  name: aws
  runtime: nodejs20.x
  httpApi:
    cors:
      allowedOrigins:
        - 'https://admin.podtree.ca' # Replace with your allowed origin(s)
      allowedHeaders:
        - 'Content-Type'
        - 'Authorization'
        - 'schoolId'
        - 'userId'
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
  iam:
    role:
      name: podtree-serverless-lambda-role
      statements:
        - Effect: Allow
          Action:
            - lambda:InvokeFunction
            - lambda:InvokeAsync
          Resource: "*"
          
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: "*"
functions:
  auth:
    handler: lambdas/auth/index.handler
    layers:
      - { Ref: MongodbLayerLambdaLayer }
    events:
      - httpApi:
          path: /login
          method: post
      - httpApi:
          path: /signup
          method: post
      - httpApi:
          path: /verify-passcode
          method: post
  staff:
    handler: lambdas/staff/index.handler
    layers:
      - { Ref: MongodbLayerLambdaLayer }
    events:
      - httpApi:
          path: /staffs
          method: get
      - httpApi:
          path: /staffs
          method: post
  parent:
    handler: lambdas/parent/index.handler
    layers:
      - { Ref: MongodbLayerLambdaLayer }
    events:
      - httpApi:
          path: /parents
          method: get
      - httpApi:
          path: /parents
          method: post
  student:
    handler: lambdas/student/index.handler
    layers:
      - { Ref: MongodbLayerLambdaLayer }
    events:
      - httpApi:
          path: /students
          method: get
      - httpApi:
          path: /students
          method: post
  application:
    handler: lambdas/application/index.handler
    layers:
      - { Ref: MongodbLayerLambdaLayer }
    events:
      - httpApi:
          path: /applications
          method: get
      - httpApi:
          path: /applications
          method: post
      - httpApi:
          path: /search/applications
          method: post
  program:
    handler: lambdas/program/index.handler
    layers:
      - { Ref: MongodbLayerLambdaLayer }
    events:
      - httpApi:
          path: /programs
          method: get
      - httpApi:
          path: /programs
          method: post
      - httpApi:
          path: /search/programs
          method: post
  invoice:
    handler: lambdas/invoice/index.handler
    events:
      - httpApi:
          path: /invoices
          method: get
      - httpApi:
          path: /search/invoices
          method: post
  charge:
    handler: lambdas/charge/index.handler
    events:
      - httpApi:
          path: /charges
          method: get
      - httpApi:
          path: /search/charges
          method: post

  chargeTemplate:
    handler: lambdas/chargeTemplate/index.handler
    events:
      - httpApi:
          path: /chargeTemplates
          method: get
      - httpApi:
          path: /search/chargeTemplates
          method: post
      - httpApi:
          path: /chargeTemplates
          method: post
  chargePlan:
    handler: lambdas/chargePlan/index.handler
    events:
      - httpApi:
          path: /chargePlans
          method: get
      - httpApi:
          path: /search/chargePlans
          method: post
      - httpApi:
          path: /chargePlans
          method: post          
      - httpApi:
          path: /batchChargePlans
          method: post
  billing:
    handler: lambdas/billing/index.handler
    events:
      - httpApi:
          path: /billings
          method: get
      - httpApi:
          path: /search/billings
          method: post 
  school:
    handler: lambdas/school/index.handler
    events:
      - httpApi:
          path: /schools/{id}
          method: get
      - httpApi:
          path: /schools
          method: get
      - httpApi:
          path: /search/schools
          method: post
      - httpApi:
          path: /schools
          method: post
      - httpApi:
          path: /schools/{id}
          method: put